import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

const root = new URL("..", import.meta.url).pathname;
const read = (path) => readFileSync(join(root, path), "utf8");

const packageJson = JSON.parse(read("package.json"));
const layout = read("app/layout.tsx");
const page = read("app/page.tsx");
const home = read("components/personal-home.tsx");
const motionProvider = read("components/motion-provider.tsx");
const reducedMotionHook = read("components/use-client-reduced-motion.ts");
const globals = read("app/globals.css");
const vercel = read("vercel.json");
const sitemap = read("public/sitemap.xml");

test("project uses the expected public-site stack", () => {
  assert.equal(packageJson.scripts.build, "next build");
  assert.equal(packageJson.scripts.dev, "next dev");
  assert.ok(packageJson.dependencies.next);
  assert.ok(packageJson.dependencies.motion);
  assert.ok(packageJson.dependencies.lenis);
  assert.ok(packageJson.devDependencies.tailwindcss);
  assert.ok(packageJson.devDependencies["@tailwindcss/postcss"]);
});

test("App Router shell, metadata, and fonts are configured", () => {
  assert.match(layout, /export const metadata/);
  assert.match(layout, /metadataBase:\s*new URL\("https:\/\/adriangruber\.com"\)/);
  assert.match(layout, /canonical:\s*"\/"/);
  assert.match(layout, /openGraph/);
  assert.match(layout, /twitter/);
  assert.match(layout, /title:\s*"Adrian Gruber"/);
  assert.match(layout, /Geist/);
  assert.match(layout, /DM_Mono/);
  assert.match(layout, /localFont/);
  assert.match(layout, /DepartureMono-Regular\.woff2/);
  assert.match(page, /PersonalHome/);
});

test("homepage exposes the minimal personal surface", () => {
  assert.match(home, /StartupCursor/);
  assert.match(home, /startup-cursor/);
  assert.match(home, /startupCursorSize/);
  assert.match(home, /startupShrinkDuration/);
  assert.match(home, /startupCompleteHoldDuration/);
  assert.match(home, /startupDigitFadeDuration/);
  assert.match(home, /setIntroComplete/);
  assert.match(home, /feelWords/);
  assert.match(home, /TerminalWord/);
  assert.match(home, /TerminalWordPhase/);
  assert.match(home, /terminalWordInitialDelay/);
  assert.match(home, /terminalWordHoldDuration/);
  assert.match(home, /terminalWordExitDuration/);
  assert.match(home, /terminalWordEnterDuration/);
  assert.match(home, /terminalWordResolveDuration/);
  assert.match(home, /terminalWordResolveStepDuration/);
  assert.match(home, /getTerminalResolveFrames/);
  assert.match(home, /initialResolveDelay/);
  assert.match(home, /terminalResolveCharacters/);
  assert.match(home, /getTerminalResolveValue/);
  assert.match(home, /terminalWordMinWidth/);
  assert.match(home, /phase:\s*"idle"/);
  assert.match(home, /phase:\s*"exiting"/);
  assert.match(home, /phase:\s*"entering"/);
  assert.doesNotMatch(home, /terminalWordSignalDuration/);
  assert.doesNotMatch(home, /terminal-word-signal/);
  assert.doesNotMatch(home, /terminal-word-caret/);
  assert.doesNotMatch(home, /terminalResolveCharacters\[Math\.floor\(Math\.random/);
  assert.doesNotMatch(home, /buildTerminalWordFrames/);
  assert.doesNotMatch(home, /commonPrefixLength/);
  assert.doesNotMatch(home, /ScrambleText/);
  assert.doesNotMatch(home, /terminal-word-measure/);
  assert.doesNotMatch(home, /scrambleCycleDuration/);
  assert.match(home, /ScrambleRevealText/);
  assert.match(home, /revealKey/);
  assert.match(home, /introRevealing/);
  assert.match(home, /introActive/);
  assert.match(home, /interactionsEnabled/);
  assert.match(home, /handleIntroComplete = useCallback/);
  assert.match(home, /handleIntroReveal = useCallback/);
  assert.match(home, /onComplete=\{handleIntroComplete\}/);
  assert.match(home, /onReveal=\{handleIntroReveal\}/);
  assert.doesNotMatch(home, /onComplete=\{\(\) => setIntroComplete/);
  assert.doesNotMatch(home, /onReveal=\{\(\) => setIntroRevealing/);
  assert.match(home, /cursorDragging/);
  assert.match(home, /targetDragActiveRef/);
  assert.match(home, /suppressClickRef/);
  assert.match(home, /onReveal/);
  assert.match(home, /pointerEvents:\s*interactionsEnabled \? "auto" : "none"/);
  assert.match(home, /pointerEvents:\s*interactive \? "auto" : "none"/);
  assert.match(home, /usePathname/);
  assert.match(home, /getTextSegments/);
  assert.match(home, /headline-line/);
  assert.match(home, /scramble-word-slot/);
  assert.match(home, /scramble-measure/);
  assert.match(home, /\{segment\.text\}/);
  assert.doesNotMatch(home, /scrambleCharacters/);
  assert.match(home, /scrambleRevealText/);
  assert.match(home, /getCalmScrambleCharacter/);
  assert.match(home, /personal-title/);
  assert.match(home, /personal-meta/);
  assert.doesNotMatch(home, /<p className="personal-meta font-mono" aria-label/);
  assert.match(home, /mailto:hello@adriangruber\.com/);
  assert.match(home, /https:\/\/github\.com\/thegruber/);
  assert.match(home, /https:\/\/www\.linkedin\.com\/in\/adrian-gruber/);
  assert.match(home, /label="GitHub"/);
  assert.match(home, /text="github"/);
  assert.match(home, /label="LinkedIn"/);
  assert.match(home, /text="linkedin"/);
});

test("motion system has reduced-motion fallbacks and cursor wiring", () => {
  assert.match(motionProvider, /new Lenis/);
  assert.match(motionProvider, /prefers-reduced-motion:\s*reduce/);
  assert.match(reducedMotionHook, /matchMedia\("\(prefers-reduced-motion:\s*reduce\)"\)/);
  assert.match(home, /useClientReducedMotion/);
  assert.match(home, /requestAnimationFrame\(update\)/);
  assert.match(home, /cancelAnimationFrame\(frameId\)/);
  assert.match(home, /useSpring/);
  assert.match(home, /frame\.read/);
  assert.match(home, /addEventListener\("pointermove"/);
  assert.match(home, /getBoundingClientRect/);
  assert.match(home, /CursorTextTarget/);
  assert.match(home, /window\.innerWidth \/ 2/);
  assert.match(home, /window\.innerHeight \/ 2/);
  assert.match(home, /String\(count\)\.padStart\(3,\s*"0"\)/);
  assert.doesNotMatch(home, /"✓"/);
  assert.doesNotMatch(home, /startupCheck/);
  assert.match(home, /setPhase\("settling"\);\s*onReveal\(\);/);
  assert.match(home, /completeTimeout = window\.setTimeout\(\(\) => \{\s*onComplete\(\);/);
  assert.match(home, /data-cursor-text/);
  assert.match(home, /text-cursor-zone/);
  assert.match(home, /getTextCursorLineHeight/);
  assert.match(home, /getTextCursorLineMetrics/);
  assert.match(home, /getClientRects/);
  assert.match(home, /horizontalHit/);
  assert.match(home, /cursorTextMaxWidth/);
  assert.match(home, /cursorTextMinWidth/);
  assert.match(home, /cursorTextFill/);
  assert.match(home, /getTextCursorVisualHeight/);
  assert.match(home, /cursorTargetSnapDuration/);
  assert.match(home, /targetGestureActiveRef/);
  assert.match(home, /useMotionValue/);
  assert.match(home, /animate\(x,\s*0,\s*\{\s*type:\s*"spring",\s*stiffness:\s*520,\s*damping:\s*22\s*\}\)/);
  assert.match(home, /animate\(y,\s*0,\s*\{\s*type:\s*"spring",\s*stiffness:\s*520,\s*damping:\s*22\s*\}\)/);
  assert.match(home, /CursorLink/);
  assert.match(home, /activeDragRef/);
  assert.match(home, /cleanupDragRef/);
  assert.match(home, /handleTargetPointerDown/);
  assert.match(home, /handleTargetDragStart/);
  assert.match(home, /handleTargetDragEnd/);
  assert.match(home, /handleTargetPointerRelease/);
  assert.match(home, /window\.addEventListener\("pointermove",\s*handlePointerMove,\s*\{\s*passive:\s*false\s*\}\)/);
  assert.match(home, /x\.set\(deltaX\)/);
  assert.match(home, /y\.set\(deltaY\)/);
  assert.match(home, /style=\{\{\s*x,\s*y\s*\}\}/);
  assert.match(home, /animate=\{\{\s*scale:\s*dragging \? 1\.035 : 1\s*\}\}/);
  assert.match(home, /draggable:\s*false/);
  assert.match(home, /onPointerDown:\s*handleTargetPointerDown/);
  assert.match(home, /onManualDragEnd:\s*handleTargetDragEnd/);
  assert.match(home, /onManualDragStart:\s*handleTargetDragStart/);
  assert.match(home, /motion\.a/);
  const targetPointerDownBody =
    home.match(/function handleTargetPointerDown[\s\S]*?\n  }\n\n  function handleTargetDragStart/)?.[0] ?? "";
  assert.doesNotMatch(targetPointerDownBody, /event\.preventDefault/);
  assert.doesNotMatch(home, /dragConstraints/);
  assert.doesNotMatch(home, /dragElastic/);
  assert.doesNotMatch(home, /useDragControls/);
  assert.doesNotMatch(home, /dragListener/);
  assert.match(home, /soft-cursor/);
  assert.match(home, /is-target/);
  assert.match(home, /is-text/);
  assert.match(home, /is-dragging/);
});

test("visual system and deployment assets are preserved", () => {
  assert.match(globals, /@import "tailwindcss"/);
  assert.match(globals, /--color-paper:/);
  assert.match(globals, /--font-main:/);
  assert.match(globals, /\.home-canvas/);
  assert.match(globals, /\.personal-canvas[\s\S]*background:\s*var\(--color-paper\)/);
  assert.doesNotMatch(globals, /\.personal-canvas::before/);
  assert.doesNotMatch(globals, /\.personal-canvas::after/);
  assert.doesNotMatch(globals, /ambient-field-one/);
  assert.doesNotMatch(globals, /ambient-field-two/);
  assert.match(globals, /--frame-text-size:\s*0\.96rem/);
  assert.match(globals, /\.cursor-link[\s\S]*font-size:\s*var\(--frame-text-size\)/);
  assert.match(globals, /\.cursor-link[\s\S]*--cursor-target-hit-x:\s*0\.62em/);
  assert.match(globals, /\.cursor-link[\s\S]*--cursor-target-hit-y:\s*0\.32em/);
  assert.match(globals, /\.cursor-link[\s\S]*margin:\s*calc\(var\(--cursor-target-hit-y\) \* -1\) calc\(var\(--cursor-target-hit-x\) \* -1\)/);
  assert.match(globals, /\.cursor-link[\s\S]*padding:\s*var\(--cursor-target-hit-y\) var\(--cursor-target-hit-x\)/);
  assert.match(globals, /\.cursor-link[\s\S]*touch-action:\s*none/);
  assert.match(globals, /\.cursor-link[\s\S]*user-select:\s*none/);
  assert.match(globals, /\.cursor-link[\s\S]*-webkit-user-select:\s*none/);
  assert.match(globals, /\.cursor-link[\s\S]*-webkit-user-drag:\s*none/);
  assert.match(globals, /\.startup-cursor[\s\S]*position:\s*fixed/);
  assert.match(globals, /\.startup-cursor[\s\S]*pointer-events:\s*none/);
  assert.match(globals, /\.startup-cursor-dot[\s\S]*background:\s*var\(--color-ink\)/);
  assert.match(globals, /\.startup-cursor-dot[\s\S]*translate:\s*-50% -50%/);
  assert.match(globals, /\.startup-cursor-value[\s\S]*font-variant-numeric:\s*tabular-nums/);
  assert.match(globals, /\.startup-cursor-value\s*\{[^}]*font-weight:\s*500/);
  assert.match(globals, /\.personal-frame[\s\S]*align-items:\s*center/);
  assert.match(globals, /\.terminal-word[\s\S]*display:\s*inline-grid/);
  assert.match(globals, /\.terminal-word[\s\S]*position:\s*relative/);
  assert.match(globals, /\.terminal-word-value[\s\S]*grid-area:\s*1 \/ 1/);
  assert.match(globals, /\.terminal-word-value[\s\S]*will-change:\s*clip-path, opacity, transform/);
  assert.match(globals, /\.terminal-word\.is-exiting \.terminal-word-value/);
  assert.match(globals, /\.terminal-word\.is-entering \.terminal-word-value/);
  assert.match(globals, /@keyframes terminal-word-dissolve-out/);
  assert.match(globals, /@keyframes terminal-word-reveal-in/);
  assert.match(globals, /\.terminal-word\.is-entering \.terminal-word-value[\s\S]*terminal-word-reveal-in/);
  assert.match(globals, /@keyframes terminal-word-reveal-in[\s\S]*opacity:\s*1/);
  assert.match(globals, /@keyframes terminal-word-reveal-in[\s\S]*clip-path:\s*inset\(0 0 0 0\)/);
  assert.doesNotMatch(globals, /@keyframes terminal-word-dissolve-in/);
  assert.doesNotMatch(globals, /opacity:\s*0\.42/);
  assert.doesNotMatch(globals, /\.terminal-word-signal/);
  assert.doesNotMatch(globals, /\.terminal-word-caret/);
  assert.doesNotMatch(globals, /terminal-glyph-resolve/);
  assert.doesNotMatch(globals, /terminal-signal-sweep/);
  assert.doesNotMatch(globals, /@keyframes terminal-caret/);
  assert.doesNotMatch(globals, /\.terminal-word-measure/);
  assert.doesNotMatch(globals, /\.scramble-text/);
  assert.match(globals, /\.scramble-reveal-text/);
  assert.match(globals, /\.scramble-word-slot[\s\S]*display:\s*inline-grid/);
  assert.match(globals, /\.scramble-word-slot[\s\S]*position:\s*relative/);
  assert.match(globals, /\.scramble-word-slot > \.scramble-value[\s\S]*position:\s*absolute/);
  assert.match(globals, /\.scramble-measure[\s\S]*visibility:\s*hidden/);
  assert.match(globals, /\.scramble-value[\s\S]*white-space:\s*pre/);
  assert.match(globals, /\.text-cursor-zone[\s\S]*display:\s*inline/);
  assert.match(globals, /\.headline-line[\s\S]*white-space:\s*nowrap/);
  assert.match(globals, /\.soft-cursor\s*\{[\s\S]*background-image:\s*none/);
  assert.match(globals, /\.soft-cursor\s*\{[\s\S]*box-shadow:\s*none/);
  assert.match(globals, /\.soft-cursor\.is-target[\s\S]*cursor-paint-shell/);
  assert.match(globals, /\.soft-cursor\.is-target\.is-dragging[\s\S]*animation-duration:\s*1\.35s/);
  assert.match(globals, /\.soft-cursor\.is-text[\s\S]*z-index:\s*65/);
  assert.match(globals, /\.soft-cursor\.is-text[\s\S]*mix-blend-mode:\s*normal/);
  assert.doesNotMatch(globals, /\.soft-cursor\.is-text::before/);
  assert.doesNotMatch(globals, /\.soft-cursor\.is-text::after/);
  assert.match(globals, /@media\s*\(prefers-reduced-motion:\s*reduce\)/);
  assert.match(home, /#245cff/);
  assert.match(globals, /#2867b2/);
  assert.match(globals, /#000000/);
  assert.match(globals, /#0fbf3e/);
  assert.match(vercel, /Content-Security-Policy/);
  assert.match(vercel, /X-Frame-Options/);
  assert.ok(existsSync(join(root, "public/robots.txt")));
  assert.ok(existsSync(join(root, "public/sitemap.xml")));
  assert.ok(existsSync(join(root, "public/favicon.svg")));
});

test("site exposes only the homepage route for now", () => {
  assert.equal(existsSync(join(root, "app/work/page.tsx")), false);
  assert.equal(existsSync(join(root, "components/work-data.ts")), false);
  assert.equal(existsSync(join(root, "components/work-index.tsx")), false);
  assert.doesNotMatch(home, /href="\/work"|href=\{workHref\}|WorkIndex|workItems/);
  assert.doesNotMatch(globals, /\.work-page|\.work-index|\.work-row|\.work-detail/);
  assert.doesNotMatch(sitemap, /\/work/);
});
