import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

const root = new URL("..", import.meta.url).pathname;
const read = (path) => readFileSync(join(root, path), "utf8");

const packageJson = JSON.parse(read("package.json"));
const layout = read("app/layout.tsx");
const page = read("app/page.tsx");
const home = read("components/personal-home.tsx");
const motionProvider = read("components/motion-provider.tsx");
const reducedMotionHook = read("components/use-client-reduced-motion.ts");
const globals = read("app/globals.css");
const vercel = read("vercel.json");
const sitemap = read("public/sitemap.xml");

test("Next app uses the selected premium stack", () => {
  assert.equal(packageJson.scripts.build, "next build");
  assert.equal(packageJson.scripts.dev, "next dev");
  assert.ok(packageJson.dependencies.next);
  assert.ok(packageJson.dependencies.motion);
  assert.ok(packageJson.dependencies.lenis);
  assert.ok(packageJson.devDependencies.tailwindcss);
  assert.ok(packageJson.devDependencies["@tailwindcss/postcss"]);
  assert.equal(packageJson.overrides.postcss, "^8.5.15");
});

test("App Router metadata and fonts are configured", () => {
  assert.match(layout, /export const metadata/);
  assert.match(layout, /metadataBase:\s*new URL\("https:\/\/adriangruber\.com"\)/);
  assert.match(layout, /canonical:\s*"\/"/);
  assert.match(layout, /openGraph/);
  assert.match(layout, /title:\s*"Adrian Gruber"/);
  assert.doesNotMatch(layout, /Pinio|Linkpeek/);
  assert.match(layout, /icons/);
  assert.match(layout, /favicon\.svg/);
  assert.match(layout, /Geist/);
  assert.match(layout, /DM_Mono/);
  assert.match(layout, /localFont/);
  assert.match(layout, /DepartureMono-Regular\.woff2/);
  assert.match(page, /PersonalHome/);
});

test("homepage renders personal copy and one-screen personal surface", () => {
  assert.match(home, /I design and build products that look sharp, feel natural, and make sense/);
  assert.match(home, /UX\/UI, frontend, product systems, and useful automation\. Based in Europe/);
  assert.match(home, /design \/ code \/ products/);
  assert.match(home, /https:\/\/github\.com\/thegruber/);
  assert.match(home, /https:\/\/www\.linkedin\.com\/in\/adrian-gruber/);
  assert.match(home, />\s*github\s*</);
  assert.match(home, />\s*linkedin\s*</);
  assert.doesNotMatch(home, />\s*Mail\s*</);
  assert.doesNotMatch(home, /distribution|craft systems|studio index|pinio index/i);
  assert.doesNotMatch(home, /small, useful products|small useful products|focus on feel/i);
  assert.doesNotMatch(home, /\bwork\b/);
  assert.match(home, /contact/);
  assert.doesNotMatch(home, /workHref/);
  assert.doesNotMatch(home, /href=\{workHref\}/);
  assert.doesNotMatch(home, /href="\/work"/);
  assert.doesNotMatch(home, /prefetch=\{false\}/);
  assert.doesNotMatch(home, /workItems/);
  assert.doesNotMatch(home, /activeWork/);
  assert.match(home, /cursorHandlers/);
  assert.match(home, /setCursorAround/);
  assert.match(home, /CursorTarget/);
  assert.doesNotMatch(home, /label:\s*element\.textContent\?\.trim\(\)/);
  assert.doesNotMatch(home, /soft-cursor-label/);
  assert.doesNotMatch(home, /cursorVisualBleed/);
  assert.doesNotMatch(home, /data-cursor-active/);
  assert.doesNotMatch(home, /clampToRange/);
  assert.doesNotMatch(home, /home-work-rail/);
  assert.doesNotMatch(home, /work-chip/);
  assert.doesNotMatch(home, /WorkPreview/);
  assert.doesNotMatch(home, /Pinio|Linkpeek/);
  assert.doesNotMatch(home, /setCursorAccent/);
  assert.doesNotMatch(home, /guba\.studio/);
  assert.doesNotMatch(home, /Barcelona/);
  assert.match(home, /Based in Europe/);
  assert.doesNotMatch(home, /independent/i);
  assert.doesNotMatch(home, /Madrid \/ 2026/);
  assert.match(home, /mailto:hello@adriangruber\.com/);
  assert.match(home, /className="cursor-link"/);
  assert.doesNotMatch(home, /SignatureMark/);
  assert.match(home, /reveal-clip/);
  assert.doesNotMatch(home, /pixel-work/);
  assert.doesNotMatch(home, /DotMatrixSignature/);
  assert.doesNotMatch(home, /never have i ever|consumer app scout|private experiments/i);
  assert.doesNotMatch(home, /SignalBoard|WorkPattern/);
  assert.doesNotMatch(home, /founder|solo/);
});

test("motion system uses Lenis, Motion, and reduced-motion fallbacks", () => {
  assert.match(motionProvider, /new Lenis/);
  assert.match(motionProvider, /prefers-reduced-motion:\s*reduce/);
  assert.doesNotMatch(home, /useMotionValue/);
  assert.doesNotMatch(home, /useMotionTemplate/);
  assert.match(home, /useSpring/);
  assert.doesNotMatch(home, /useTransform/);
  assert.match(home, /frame\.read/);
  assert.match(home, /useClientReducedMotion/);
  assert.match(reducedMotionHook, /matchMedia\("\(prefers-reduced-motion:\s*reduce\)"\)/);
  assert.match(home, /function useFollowCursor/);
  assert.match(home, /addEventListener\("pointermove"/);
  assert.doesNotMatch(home, /passive:\s*true/);
  assert.match(home, /onPointerMove=\{handlePointerMove\}/);
  assert.match(home, /onPointerDown/);
  assert.match(home, /const cursorSpring = \{ damping: 30, stiffness: 620, mass: 0\.55 \}/);
  assert.doesNotMatch(home, /liquidSpring/);
  assert.doesNotMatch(home, /liquidX/);
  assert.doesNotMatch(home, /liquidY/);
  assert.doesNotMatch(home, /liquidSpin/);
  assert.doesNotMatch(home, /cursorWidth/);
  assert.doesNotMatch(home, /cursorHeight/);
  assert.doesNotMatch(home, /cursorRadius/);
  assert.match(home, /const ref = useRef<HTMLDivElement>\(null\)/);
  assert.match(home, /const \{ x, y, width, height, radius \} = useFollowCursor\(ref, target\)/);
  assert.match(home, /const x = useSpring\(-80, cursorSpring\)/);
  assert.match(home, /const y = useSpring\(-80, cursorSpring\)/);
  assert.match(home, /clientX - element\.offsetLeft - cursorSize \/ 2/);
  assert.match(home, /clientY - element\.offsetTop - cursorSize \/ 2/);
  assert.match(home, /x:\s*x/);
  assert.match(home, /y:\s*y/);
  assert.match(home, /ref=\{ref\}/);
  assert.doesNotMatch(home, /left:\s*cursorLeft/);
  assert.doesNotMatch(home, /top:\s*cursorTop/);
  assert.match(home, /width:\s*width/);
  assert.match(home, /height:\s*height/);
  assert.match(home, /cursorFill/);
  assert.match(home, /getPropertyValue\("--link-liquid-fill"\)/);
  assert.match(home, /getPropertyValue\("--link-liquid-text"\)/);
  assert.match(home, /const cursorTargetPadding = 9/);
  assert.match(home, /const cursorTargetRadius = 21/);
  assert.doesNotMatch(home, /cursor-paint-filter/);
  assert.doesNotMatch(home, /cursor-paint-drop/);
  assert.doesNotMatch(home, /feGaussianBlur/);
  assert.doesNotMatch(home, /feMerge/);
  assert.doesNotMatch(home, /feTurbulence/);
  assert.doesNotMatch(home, /feDisplacementMap/);
  assert.doesNotMatch(home, /cursorStretched/);
  assert.doesNotMatch(home, /pulseCursor/);
  assert.doesNotMatch(home, /magneticSnap/);
  assert.doesNotMatch(home, /minWidth:\s*0/);
  assert.doesNotMatch(home, /minHeight:\s*34/);
  assert.doesNotMatch(home, /padding:\s*10/);
  assert.match(home, /getBoundingClientRect/);
  assert.match(home, /const targetWidth = rect\.width \+ target\.padding \* 2/);
  assert.match(home, /const targetHeight = rect\.height \+ target\.padding \* 2/);
  assert.match(home, /const targetX = rect\.left \+ rect\.width \/ 2/);
  assert.match(home, /const targetY = rect\.top \+ rect\.height \/ 2/);
  assert.doesNotMatch(home, /cursorX\.set/);
  assert.doesNotMatch(home, /cursorY\.set/);
  assert.match(home, /soft-cursor/);
  assert.match(home, /is-target/);
  assert.doesNotMatch(home, /soft-cursor-target/);
  assert.doesNotMatch(home, /data-work-cursor/);
  assert.doesNotMatch(home, /personal-field/);
  assert.doesNotMatch(home, /setFieldOpacity/);
  assert.doesNotMatch(home, /setFieldFromPointer/);
  assert.doesNotMatch(home, /soft-cursor-dot/);
  assert.match(globals, /@media\s*\(prefers-reduced-motion:\s*reduce\)/);
});

test("Tailwind tokens and deployment assets are preserved", () => {
  assert.match(globals, /@import "tailwindcss"/);
  assert.match(globals, /--color-paper:/);
  assert.match(globals, /--color-accent:/);
  assert.match(globals, /--font-main:/);
  assert.match(globals, /\.home-canvas/);
  assert.match(globals, /\.personal-frame[\s\S]*height:\s*100svh/);
  assert.match(globals, /\.personal-frame[\s\S]*z-index:\s*40/);
  assert.match(globals, /\.personal-frame[\s\S]*pointer-events:\s*none/);
  assert.match(globals, /\.personal-hero/);
  assert.doesNotMatch(globals, /\.personal-field/);
  assert.doesNotMatch(globals, /--field-opacity/);
  assert.doesNotMatch(globals, /fractalNoise/);
  assert.doesNotMatch(globals, /--font-pixel/);
  assert.doesNotMatch(globals, /\.font-pixel/);
  assert.doesNotMatch(globals, /\.slash-mark/);
  assert.doesNotMatch(globals, /\.smile-mark/);
  assert.doesNotMatch(globals, /--color-paper-2/);
  assert.doesNotMatch(globals, /--color-red-deep/);
  assert.doesNotMatch(globals, /--color-plum/);
  assert.doesNotMatch(globals, /--color-signal-blue/);
  assert.match(globals, /\.personal-socials/);
  assert.match(home, /social-link-github/);
  assert.match(home, /social-link-linkedin/);
  assert.match(globals, /\.personal-footer a[\s\S]*color:\s*var\(--color-ink\)/);
  assert.match(globals, /\.cursor-link:hover[\s\S]*transition-delay:\s*90ms/);
  assert.match(globals, /\.personal-footer \.social-link:hover[\s\S]*color:\s*var\(--social-text\)/);
  assert.match(globals, /\.personal-footer \.social-link:hover[\s\S]*transition-delay:\s*90ms/);
  assert.doesNotMatch(globals, /\.personal-footer \.social-link\s*\{[\s\S]*color:\s*var\(--social-fill\)/);
  assert.match(globals, /#0a66c2/);
  assert.match(globals, /#1f2328/);
  assert.match(globals, /#3fb950/);
  assert.match(globals, /--social-text:\s*var\(--color-paper\)/);
  assert.match(globals, /\.social-link[\s\S]*--social-fill:\s*var\(--color-ink\)/);
  assert.match(globals, /\.social-link[\s\S]*--link-liquid-fill:\s*var\(--social-fill\)/);
  assert.match(globals, /\.social-link[\s\S]*--link-liquid-text:\s*var\(--social-text\)/);
  assert.match(globals, /\.social-link-github[\s\S]*--social-fill:\s*#1f2328/);
  assert.match(globals, /\.social-link-github[\s\S]*--social-text:\s*#3fb950/);
  assert.match(globals, /\.social-link-linkedin[\s\S]*--social-fill:\s*#0a66c2/);
  assert.match(globals, /\.social-link-linkedin[\s\S]*--social-text:\s*#ffffff/);
  assert.doesNotMatch(globals, /\.soft-cursor\[data-brand-cursor="true"\]/);
  assert.match(globals, /\.personal-footer[\s\S]*z-index:\s*40/);
  assert.match(globals, /\.personal-footer[\s\S]*pointer-events:\s*auto/);
  assert.match(globals, /\.soft-cursor[\s\S]*z-index:\s*30/);
  assert.doesNotMatch(globals, /\.soft-cursor\[[^\]]+\]\s*\{[^}]*z-index:\s*30/);
  assert.doesNotMatch(globals, /\.soft-cursor\[data-work-cursor="true"\]/);
  assert.match(globals, /will-change:\s*transform/);
  assert.doesNotMatch(globals, /--liquid-x:\s*0px/);
  assert.doesNotMatch(globals, /--liquid-y:\s*0px/);
  assert.doesNotMatch(globals, /--liquid-spin:\s*0deg/);
  assert.doesNotMatch(globals, /\.soft-cursor-core[\s\S]*inset:\s*0/);
  assert.doesNotMatch(globals, /--cursor-bleed/);
  assert.doesNotMatch(globals, /calc\(var\(--cursor-bleed\)/);
  assert.doesNotMatch(globals, /conic-gradient\(\s*from var\(--liquid-spin\) at 50% 50%/);
  assert.doesNotMatch(globals, /#ff3b30 360deg/);
  assert.doesNotMatch(globals, /\.soft-cursor-core::before/);
  assert.doesNotMatch(globals, /@keyframes liquid-cursor-circulate/);
  assert.doesNotMatch(globals, /animation:\s*liquid-cursor-circulate/);
  assert.doesNotMatch(globals, /@keyframes work-cursor-flow/);
  assert.doesNotMatch(globals, /width:\s*1000%/);
  assert.doesNotMatch(globals, /translate3d\(-90%, 0, 0\)/);
  assert.doesNotMatch(globals, /@keyframes living-cursor-blob-core/);
  assert.doesNotMatch(globals, /@keyframes living-cursor-soft-core/);
  assert.doesNotMatch(globals, /@keyframes living-cursor-signature-core/);
  assert.doesNotMatch(globals, /\.soft-cursor\[data-cursor-accent="contact"\][\s\S]*mix-blend-mode:\s*normal/);
  assert.doesNotMatch(globals, /cursor-pixel-drift/);
  assert.doesNotMatch(globals, /image-rendering:\s*pixelated/);
  assert.doesNotMatch(globals, /\.soft-cursor-edge/);
  assert.doesNotMatch(globals, /\.soft-cursor-halo/);
  assert.doesNotMatch(globals, /\.soft-cursor-core::after/);
  assert.doesNotMatch(globals, /@keyframes living-cursor-light/);
  assert.match(globals, /animation-duration:\s*1ms !important/);
  assert.doesNotMatch(globals, /background-position:\s*100% 50%/);
  assert.match(globals, /\.cursor-link/);
  assert.match(globals, /--link-liquid-text:\s*var\(--color-paper\)/);
  assert.doesNotMatch(globals, /\.cursor-link::before/);
  assert.doesNotMatch(globals, /@keyframes link-liquid-wobble/);
  assert.doesNotMatch(globals, /@keyframes cursor-liquid-morph/);
  assert.match(globals, /\.soft-cursor\.is-target/);
  assert.doesNotMatch(globals, /animation:\s*cursor-liquid-morph/);
  assert.match(globals, /\.soft-cursor\.is-target[\s\S]*animation:\s*cursor-paint-shell 2\.6s/);
  assert.doesNotMatch(globals, /\.soft-cursor\.is-target[\s\S]*filter:\s*url/);
  assert.match(globals, /@keyframes cursor-paint-shell/);
  assert.match(globals, /border-radius:\s*54% 46% 50% 50% \/ 46% 58% 42% 54%/);
  assert.match(globals, /border-radius:\s*44% 56% 61% 39% \/ 58% 43% 57% 42%/);
  assert.doesNotMatch(globals, /clip-path:\s*polygon/);
  assert.doesNotMatch(globals, /\.cursor-paint-filter/);
  assert.match(home, /borderRadius:\s*radius/);
  assert.doesNotMatch(globals, /\.cursor-link\[data-cursor-active="true"\]/);
  assert.match(globals, /\.cursor-link[\s\S]*font-size:\s*0\.96rem/);
  assert.match(globals, /\.cursor-link[\s\S]*line-height:\s*1\.35/);
  assert.match(globals, /\.personal-footer[\s\S]*font-size:\s*0\.96rem/);
  assert.match(globals, /\.reveal-clip/);
  assert.doesNotMatch(globals, /\.home-work-rail/);
  assert.doesNotMatch(globals, /\.work-chip/);
  assert.doesNotMatch(globals, /\.work-peek/);
  assert.doesNotMatch(globals, /--cursor-fill/);
  assert.doesNotMatch(globals, /\.signature-dots/);
  assert.doesNotMatch(globals, /\.work-page/);
  assert.doesNotMatch(globals, /\.work-index/);
  assert.doesNotMatch(globals, /\.work-preview-card/);
  assert.doesNotMatch(globals, /\.work-row/);
  assert.doesNotMatch(globals, /\.work-detail/);
  assert.doesNotMatch(globals, /\.work-signal/);
  assert.doesNotMatch(globals, /\.pixel-work/);
  assert.doesNotMatch(globals, /\.dot-signature/);
  assert.doesNotMatch(globals, /@keyframes dot-breathe/);
  assert.doesNotMatch(globals, /\.work-object/);
  assert.doesNotMatch(globals, /\.cloud-stage/);
  assert.doesNotMatch(globals, /\.cloud-art/);
  assert.doesNotMatch(globals, /\.personal-work-link/);
  assert.match(globals, /\.soft-cursor/);
  assert.match(globals, /\.soft-cursor[\s\S]*border:\s*0/);
  assert.match(globals, /\.soft-cursor[\s\S]*background:\s*#000000/);
  assert.doesNotMatch(globals, /translate:\s*-50% -50%/);
  assert.match(globals, /\.soft-cursor[\s\S]*left:\s*0/);
  assert.match(globals, /\.soft-cursor[\s\S]*top:\s*0/);
  assert.match(home, /backgroundColor:\s*cursorFill/);
  assert.doesNotMatch(globals, /\.soft-cursor-target/);
  assert.doesNotMatch(globals, /rgb\(255 255 255 \/ 88%\)/);
  assert.doesNotMatch(globals, /rgb\(255 255 255 \/ 90%\)/);
  assert.doesNotMatch(globals, /contain:\s*layout style/);
  assert.doesNotMatch(globals, /\.soft-cursor-label[\s\S]*z-index:\s*1/);
  assert.doesNotMatch(globals, /\.soft-cursor-label[\s\S]*color:\s*var\(--cursor-label\)/);
  assert.doesNotMatch(globals, /contain:\s*layout paint style/);
  assert.match(globals, /\.soft-cursor[\s\S]*mix-blend-mode:\s*normal/);
  assert.doesNotMatch(globals, /\.soft-cursor[^{}]*\{[^}]*mix-blend-mode:\s*difference/);
  assert.doesNotMatch(home, /acid:\s*"#3800b0"/);
  assert.doesNotMatch(home, /contact:\s*"#000000"/);
  assert.doesNotMatch(home, /work:\s*"#c7ff4f"/);
  assert.doesNotMatch(globals, /\.soft-cursor\[data-cursor-accent="github"\] \.soft-cursor-core/);
  assert.doesNotMatch(globals, /\.soft-cursor\[data-cursor-accent="linkedin"\] \.soft-cursor-core/);
  assert.doesNotMatch(globals, /\.soft-cursor-core[\s\S]*background:\s*var\(--cursor-fill\)/);
  assert.doesNotMatch(globals, /\.soft-cursor\[data-cursor-accent="contact"\] \.soft-cursor-core[\s\S]*background:\s*#000000/);
  assert.doesNotMatch(globals, /\.soft-cursor\[data-cursor-accent="signature"\] \.soft-cursor-core[\s\S]*background:\s*#000000/);
  assert.doesNotMatch(globals, /#e8f4ff/);
  assert.doesNotMatch(globals, /\.soft-cursor(?:\[[^\]]+\])? \.soft-cursor-core\s*\{[^}]*rgb\([^)]*\/\s*\d+%[^}]*\}/);
  assert.doesNotMatch(home, /soft-cursor-edge/);
  assert.doesNotMatch(home, /soft-cursor-halo/);
  assert.doesNotMatch(home, /soft-cursor-pixel-field/);
  assert.doesNotMatch(globals, /\.soft-cursor-dot/);
  assert.doesNotMatch(globals, /\.soft-cursor-open/);
  assert.doesNotMatch(globals, /\.soft-cursor-link/);
  assert.doesNotMatch(globals, /\.hero-stage::before/);
  assert.doesNotMatch(globals, /\.black-footer::before/);
  assert.doesNotMatch(globals, /\.footer-line/);
  assert.doesNotMatch(sitemap, /https:\/\/adriangruber\.com\/work/);
  assert.match(sitemap, /<lastmod>2026-06-04<\/lastmod>/);
  assert.match(vercel, /Content-Security-Policy/);
  assert.match(vercel, /X-Frame-Options/);
  assert.ok(existsSync(join(root, "public/robots.txt")));
  assert.ok(existsSync(join(root, "public/sitemap.xml")));
  assert.ok(existsSync(join(root, "public/favicon.svg")));
  assert.equal(existsSync(join(root, "components/reveal.tsx")), false);
  assert.equal(existsSync(join(root, "components/signal-board.tsx")), false);
  assert.equal(existsSync(join(root, "robots.txt")), false);
  assert.equal(existsSync(join(root, "sitemap.xml")), false);
  assert.equal(existsSync(join(root, "public/styles.css")), false);
  assert.equal(existsSync(join(root, "legal/never-have-i-ever/privacy.html")), false);
  assert.equal(existsSync(join(root, "public/legal/never-have-i-ever/privacy.html")), false);
  assert.equal(existsSync(join(root, "docs/product-design-audit-2026-06-03/audit.md")), false);
  assert.equal(existsSync(join(root, "docs/superpowers/plans/2026-06-02-personal-site-work-index.md")), false);
  assert.equal(existsSync(join(root, "app/work/page.tsx")), false);
  assert.equal(existsSync(join(root, "components/work-data.ts")), false);
  assert.equal(existsSync(join(root, "components/work-index.tsx")), false);
  assert.doesNotMatch(sitemap, /legal\/never-have-i-ever/);
});

test("site exposes only the homepage route for now", () => {
  assert.match(page, /PersonalHome/);
  assert.equal(existsSync(join(root, "app/work/page.tsx")), false);
  assert.equal(existsSync(join(root, "components/work-data.ts")), false);
  assert.equal(existsSync(join(root, "components/work-index.tsx")), false);
  assert.doesNotMatch(home, /href="\/work"|href=\{workHref\}|WorkIndex|workItems/);
  assert.doesNotMatch(globals, /\.work-page|\.work-index|\.work-row|\.work-detail/);
  assert.doesNotMatch(sitemap, /\/work/);
});
